#!/usr/bin/env node
/**
 * Pre-build script: reads pdfmake font files and generates a TypeScript module
 * with the font data embedded as base64 strings. This allows the bundle to work
 * without node_modules at runtime.
 */
const fs = require("fs");
const path = require("path");

const fontsDir = path.join(__dirname, "..", "node_modules", "pdfmake", "build", "fonts", "Roboto");

const fonts = {
  robotoRegular: path.join(fontsDir, "Roboto-Regular.ttf"),
  robotoBold: path.join(fontsDir, "Roboto-Medium.ttf"),
  robotoItalic: path.join(fontsDir, "Roboto-Italic.ttf"),
  robotoBoldItalic: path.join(fontsDir, "Roboto-MediumItalic.ttf"),
};

let output = "// AUTO-GENERATED by scripts/generate-fonts.js — do not edit\n\n";

for (const [name, filePath] of Object.entries(fonts)) {
  const data = fs.readFileSync(filePath);
  const base64 = data.toString("base64");
  output += `export const ${name} = Buffer.from("${base64}", "base64");\n`;
}

const outPath = path.join(__dirname, "..", "src", "pdf-fonts.ts");
fs.writeFileSync(outPath, output, "utf-8");
console.log(`Generated ${outPath} (${Object.keys(fonts).length} fonts)`);
